# Template for region-specific configuration
# This file is generated by terragrunt for each region in the environment

locals {
  environment = "${ENVIRONMENT}"
  region = "${region}"
  domain_name = "${domain_name}"
  cluster_name = "$${local.environment}-$${local.region}"
}

inputs = {
  environment = local.environment
  domain_name = local.domain_name
  hetzner_region = local.region

  # Environment-region specific cluster configuration
  cluster_name = local.cluster_name

  # Configuration based on environment
  %{ if environment == "dev" ~}
  control_plane_server_type = "cax11"
  agent_server_type = "cax11"
  control_plane_count = 1
  agent_count = 1
  %{ endif ~}

  %{ if environment == "qa" ~}
  control_plane_server_type = "cax21"
  agent_server_type = "cax21"
  control_plane_count = 1
  agent_count = 2
  %{ endif ~}

  %{ if environment == "uat" ~}
  control_plane_server_type = "cax21"
  agent_server_type = "cax21"
  control_plane_count = 1
  agent_count = 3
  %{ endif ~}

  %{ if environment == "prod" ~}
  control_plane_server_type = "cax31"
  agent_server_type = "cax31"
  control_plane_count = 3
  agent_count = 5
  %{ endif ~}
}
