# Development Environment Variables
# NOTE: Sensitive values are loaded from GitHub Secrets, not stored in this file

# Environment
environment = "dev"

# Domain Configuration
domain_name = "magebase.dev"

# Cloudflare Configuration

# AWS SES Configuration - Using dedicated SES user for dev environment
# These values are now generated by the aws-ses-users module and captured in CI/CD
# - aws_ses_access_key_id: Generated by aws-ses-users module
# - aws_ses_secret_access_key: Generated by aws-ses-users module

# Docker Configuration
docker_image = "magebase/site:dev-latest"

# Infrastructure Configuration
# These values are loaded from environment variables in CI/CD:
# - hcloud_token: From HCLOUD_TOKEN secret
# - cloudflare_api_token: From CLOUDFLARE_API_TOKEN secret
# - secret_key_base: From SECRET_KEY_BASE secret
# - ruby_llm_api_key: From RUBY_LLM_API_KEY secret
# - stripe_api_key: From STRIPE_API_KEY secret
# - stripe_webhook_secret: From STRIPE_WEBHOOK_SECRET secret
# - ssh_private_key: From SSH_PRIVATE_KEY secret
# - ssh_public_key: From SSH_PUBLIC_KEY secret
# Note: database_url is now generated by CloudNativePG operator
