# QA Environment Variables
# Replace placeholder values with your actual configuration

# Environment
environment = "qa"

# Domain Configuration
domain_name = "qa.magebase.dev"

# AWS SES Configuration - Using dedicated SES user for qa environment
# These values are now generated by the aws-ses-users module and captured in CI/CD
# - aws_ses_access_key_id: Generated by aws-ses-users module
# - aws_ses_secret_access_key: Generated by aws-ses-users module

# Database Configuration
# NOTE: With CloudNativePG, the database URL is automatically generated
# and does not need to be specified here. The application will reference
# the 'magebase-db-creds' Kubernetes Secret created by the operator.

# Cache Configuration
# SolidCache uses PostgreSQL for caching (same database as application)

# Rails Application Secrets
# Secret key base for Rails sessions and encrypted cookies
secret_key_base = "your-qa-secret-key-base-here-32-characters-minimum"

# AI Service Configuration
# API key for RubyLLM service (AI-powered pricing and contract generation)
ruby_llm_api_key = "your-ruby-llm-api-key-here"

# Docker Configuration
# Docker image tag for App Runner deployments
docker_image_tag = "qa-latest"
