apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: magebase-app-prod
  namespace: argocd
  labels:
    environment: prod
spec:
  project: default
  source:
    repoURL: https://github.com/xyz-ekrata/magebase
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: magebase-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
