name: Update ArgoCD Applications on Release

on:
  repository_dispatch:
    types: [trigger-workflow]
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository that created the release"
        required: true
        type: choice
        options:
          - magebase/genfix
          - magebase/site
      tag:
        description: "Tag to update to"
        required: true
        type: string
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - dev
          - prod
      regions:
        description: "Target regions for the environment (comma-separated)"
        required: false
        type: string

jobs:
  semantic-release:
    name: "Semantic Release"
    runs-on: ubicloud-standard-2-arm
    permissions:
      contents: write
      pull-requests: write
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run semantic-release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: main
          dry_run: ${{ github.event_name == 'pull_request' }}
          extra_plugins: |
            @semantic-release/git
            @semantic-release/github
            @semantic-release/changelog
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs for dry run
        if: github.event_name == 'pull_request'
        run: |
          echo "new_release_published=false" >> $GITHUB_OUTPUT
          echo "new_release_version=dry-run" >> $GITHUB_OUTPUT

  update-argocd-app:
    name: "Update ArgoCD Application"
    runs-on: ubicloud-standard-2-arm
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout base-infra repository
        uses: actions/checkout@v4
        with:
          repository: magebase/base-infra
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if ArgoCD update is needed
        id: should-update
        run: |
          if [ "${{ steps.repo-info.outputs.repository }}" = "magebase/base-infra" ]; then
            echo "ℹ️  Skipping ArgoCD update for base-infra release"
            echo "should_update=false" >> $GITHUB_OUTPUT
          else
            echo "should_update=true" >> $GITHUB_OUTPUT
          fi

      - name: Determine repository and application details
        id: repo-info
        run: |
          echo "🔍 Debug: Event name is ${{ github.event_name }}"
          echo "🔍 Debug: Current repository is ${{ github.repository }}"

          # Get repository name from release, repository_dispatch, or workflow dispatch
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "🔍 Debug: Release event detected"
            REPO_NAME="${{ github.repository }}"
            TAG_NAME="${{ github.event.release.tag_name }}"
            ENVIRONMENT="prod"  # Default to prod for releases in base-infra
          elif [ "${{ github.event_name }}" = "repository_dispatch" ]; then
            echo "🔍 Debug: Client payload repository: ${{ github.event.client_payload.repository }}"
            REPO_NAME="${{ github.event.client_payload.repository }}"
            TAG_NAME="${{ github.event.client_payload.tag }}"
            ENVIRONMENT="${{ github.event.client_payload.to_environment || 'prod' }}"

            # Validate that only allowed repositories can trigger this workflow
            ALLOWED_REPOS=("magebase/genfix" "magebase/site" "magebase/base-infra")
            if [[ "$REPO_NAME" != "magebase/genfix" && "$REPO_NAME" != "magebase/site" && "$REPO_NAME" != "magebase/base-infra" ]]; then
              echo "❌ Unauthorized repository: $REPO_NAME"
              echo "Allowed repositories: magebase/genfix, magebase/site, magebase/base-infra"
              exit 1
            fi

            echo "📦 Repository dispatch detected: $REPO_NAME $TAG_NAME"
          else
            echo "🔍 Debug: Workflow dispatch repository input: ${{ github.event.inputs.repository }}"
            REPO_NAME="${{ github.event.inputs.repository }}"
            TAG_NAME="${{ github.event.inputs.tag }}"
            ENVIRONMENT="${{ github.event.inputs.environment }}"

            # Validate repository name for workflow dispatch as well
            ALLOWED_REPOS=("magebase/genfix" "magebase/site" "magebase/base-infra")
            if [[ "$REPO_NAME" != "magebase/genfix" && "$REPO_NAME" != "magebase/site" && "$REPO_NAME" != "magebase/base-infra" ]]; then
              echo "❌ Invalid repository for workflow dispatch: $REPO_NAME"
              echo "Allowed repositories: magebase/genfix, magebase/site, magebase/base-infra"
              exit 1
            fi
          fi

          # Set default regions based on environment
          case "$ENVIRONMENT" in
            "dev")
              DEFAULT_REGIONS="fsn1"
              ;;
            # "qa")  # Commented out - QA deployments disabled
            #   DEFAULT_REGIONS="fsn1,nbg1"
            #   ;;
            # "uat") # Commented out - UAT deployments disabled
            #   DEFAULT_REGIONS="fsn1,nbg1,hel1"
            #   ;;
            "prod")
              DEFAULT_REGIONS="fsn1"
              ;;
            *)
              DEFAULT_REGIONS="fsn1"
              ;;
          esac

          # Use provided regions or defaults
          if [ "${{ github.event_name }}" = "repository_dispatch" ] && [ -n "${{ github.event.client_payload.regions }}" ]; then
            REGIONS="${{ github.event.client_payload.regions }}"
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.regions }}" ]; then
            REGIONS="${{ github.event.inputs.regions }}"
          else
            REGIONS="$DEFAULT_REGIONS"
          fi

          echo "Repository: $REPO_NAME"
          echo "Tag: $TAG_NAME"
          echo "Environment: $ENVIRONMENT"
          echo "Regions: $REGIONS"

          # Validate tag format (should be semantic version)
          if [[ ! "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "⚠️  Warning: Tag $TAG_NAME does not follow semantic versioning (v1.2.3)"
          fi

          # Convert comma-separated regions to array
          IFS=',' read -ra REGION_ARRAY <<< "$REGIONS"

          # Validate repository and environment combination
          case "$REPO_NAME" in
            "magebase/genfix"|"magebase/site")
              echo "✅ Valid repository for targetRevision update: $REPO_NAME"
              ;;
            "magebase/base-infra")
              # Base-infra releases don't need ArgoCD updates
              echo "ℹ️  Base-infra release - no targetRevision updates needed"
              ;;
            *)
              echo "❌ Unsupported repository: $REPO_NAME"
              exit 1
              ;;
          esac

          echo "repository=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "regions=$REGIONS" >> $GITHUB_OUTPUT

      - name: Update targetRevision in clients.json
        if: steps.should-update.outputs.should_update == 'true'
        run: |
          echo "🔍 Debug: About to update clients.json with:"
          echo "  Repository: ${{ steps.repo-info.outputs.repository }}"
          echo "  Tag: ${{ steps.repo-info.outputs.tag_name }}"
          echo "  Environment: ${{ steps.repo-info.outputs.environment }}"

          CLIENTS_FILE="infra/pipeline/base-infrastructure/clients.json"

          # Determine client name from repository
          case "${{ steps.repo-info.outputs.repository }}" in
            "magebase/genfix")
              CLIENT_NAME="genfix"
              ;;
            "magebase/site")
              CLIENT_NAME="site"
              ;;
            *)
              echo "❌ Unsupported repository: ${{ steps.repo-info.outputs.repository }}"
              exit 1
              ;;
          esac

          echo "📝 Updating targetRevision for $CLIENT_NAME in ${{ steps.repo-info.outputs.environment }} environment to ${{ steps.repo-info.outputs.tag_name }}"

          # Update the targetRevision in clients.json using jq
          jq --arg client "$CLIENT_NAME" \
             --arg env "${{ steps.repo-info.outputs.environment }}" \
             --arg tag "${{ steps.repo-info.outputs.tag_name }}" \
             'map(if .name == $client then .targetRevision[$env] = $tag else . end)' \
             "$CLIENTS_FILE" > "${CLIENTS_FILE}.tmp" && mv "${CLIENTS_FILE}.tmp" "$CLIENTS_FILE"

          echo "✅ Updated clients.json with new targetRevision"

      - name: Verify clients.json update
        if: steps.should-update.outputs.should_update == 'true'
        run: |
          echo "🔍 Verifying clients.json was updated correctly..."

          CLIENTS_FILE="infra/pipeline/base-infrastructure/clients.json"

          # Determine client name from repository
          case "${{ steps.repo-info.outputs.repository }}" in
            "magebase/genfix")
              CLIENT_NAME="genfix"
              ;;
            "magebase/site")
              CLIENT_NAME="site"
              ;;
            *)
              echo "❌ Unsupported repository: ${{ steps.repo-info.outputs.repository }}"
              exit 1
              ;;
          esac

          # Verify the targetRevision was updated
          UPDATED_TAG=$(jq -r --arg client "$CLIENT_NAME" --arg env "${{ steps.repo-info.outputs.environment }}"
            '.[] | select(.name == $client) | .targetRevision[$env]' "$CLIENTS_FILE")

          if [ "$UPDATED_TAG" = "${{ steps.repo-info.outputs.tag_name }}" ]; then
            echo "✅ Verification successful: $CLIENT_NAME targetRevision for ${{ steps.repo-info.outputs.environment }} is now $UPDATED_TAG"
          else
            echo "❌ Verification failed: Expected ${{ steps.repo-info.outputs.tag_name }}, but found $UPDATED_TAG"
            exit 1
          fi

      - name: Create pull request with the update
        if: steps.should-update.outputs.should_update == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            🚀 [${{ steps.repo-info.outputs.environment }}] Update ${{ steps.repo-info.outputs.repository }} targetRevision to ${{ steps.repo-info.outputs.tag_name }}

            This change updates clients.json to set the targetRevision for ${{ steps.repo-info.outputs.repository }}
            to use the new release ${{ steps.repo-info.outputs.tag_name }} for ${{ steps.repo-info.outputs.environment }} environment.

            Triggered by release in ${{ steps.repo-info.outputs.repository }}
          title: "🚀 [${{ steps.repo-info.outputs.environment }}] Update ${{ steps.repo-info.outputs.repository }} targetRevision to ${{ steps.repo-info.outputs.tag_name }}"
          body: |
            ## 🚀 TargetRevision Update

            This PR updates **clients.json** to set the targetRevision for **${{ steps.repo-info.outputs.repository }}** to use the new release **${{ steps.repo-info.outputs.tag_name }}**.

            ### Details
            - **Environment:** ${{ steps.repo-info.outputs.environment }}
            - **Repository:** ${{ steps.repo-info.outputs.repository }}
            - **New Version:** ${{ steps.repo-info.outputs.tag_name }}
            - **File Updated:** `infra/pipeline/base-infrastructure/clients.json`

            ### Changes
            - Updated `targetRevision.${{ steps.repo-info.outputs.environment }}` to `${{ steps.repo-info.outputs.tag_name }}` in clients.json

            ### Trigger
            - Release created in ${{ steps.repo-info.outputs.repository }}
            - Tag: ${{ steps.repo-info.outputs.tag_name }}

            ### Next Steps
            1. Review the changes
            2. Merge this PR to update the targetRevision
            3. ArgoCD applications will use the updated targetRevision via environment variables
          branch: update-targetRevision-${{ steps.repo-info.outputs.repository }}-${{ steps.repo-info.outputs.environment }}-${{ steps.repo-info.outputs.tag_name }}
          delete-branch: true
          labels: |
            automated
            targetRevision-update
            ${{ steps.repo-info.outputs.repository }}
            ${{ steps.repo-info.outputs.environment }}

      - name: Comment on release
        if: github.event_name == 'release'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🤖 **TargetRevision Update Triggered**\n\nI've created a PR in [base-infra](${{ steps.create-pr.outputs.pull-request-url }}) to update clients.json with this release.\n\n**Changes:**\n- Updated targetRevision.${{ steps.repo-info.outputs.environment }} to \`${{ steps.repo-info.outputs.tag_name }}\` in clients.json\n\nThe PR will be automatically merged once approved, and ArgoCD applications will use the updated targetRevision via environment variables.`
            })

      - name: Comment on repository dispatch
        if: github.event_name == 'repository_dispatch' && steps.should-update.outputs.should_update == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            // For repository_dispatch, we can't comment on the original release
            // This would need to be handled differently if commenting is required
            console.log('Repository dispatch detected - skipping release comment')

      - name: Output summary
        if: steps.should-update.outputs.should_update == 'true'
        run: |
          echo "🎉 **Update Summary**"
          echo "- Repository: ${{ steps.repo-info.outputs.repository }}"
          echo "- File Updated: infra/pipeline/base-infrastructure/clients.json"
          echo "- Environment: ${{ steps.repo-info.outputs.environment }}"
          echo "- New Tag: ${{ steps.repo-info.outputs.tag_name }}"
          echo "- PR Created: ${{ steps.create-pr.outputs.pull-request-url }}"
          echo ""
          echo "Next steps:"
          echo "1. Review and merge the PR"
          echo "2. ArgoCD applications will use the updated targetRevision from clients.json via environment variables"
