apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: HEAD
    chart: argo-cd
    helm:
      values: |
        server:
          service:
            type: ClusterIP
          ingress:
            enabled: true
            hosts:
              - argocd.${domain}
            tls:
              - secretName: argocd-tls
                hosts:
                  - argocd.${domain}
        configs:
          secret:
            argocdServerAdminPassword: ${argocd_admin_password}
        dex:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
